export const tables: Table[] = [
	{
		number: 1,
		guests: [
			"Salim Hassan",
			"Heidi Hassan",
			"Patricia Klemp",
			"Kara Klemp",
			"Tiffany Sun Dela Cruz",
			"Mark Geurts",
			"Daniel Staring",
			"Bethany Fuller",
			"Yasotha Anandarajah",
			"Jyot Daveta",
		],
	},
	{
		number: 2,
		guests: [
			"William Chow",
			"Stephen Chow",
			"Minho Choi",
			"Alex Labach",
			"Hamoudi El-Imam",
			"Tammy Tam",
			"Trevor Van Leeuwen",
			"Emily Ariel",
			"Ganan Gajendran",
			"Carolina Rodriguez",
		],
	},
	{
		number: 3,
		guests: [
			"Michael Stumm",
			"Mireille Broucke",
			"Jonathan Werner",
			"Melissa Campagnolo",
			"Andrew Lehan",
			"Zoe Lehan",
			"Megan Rhind",
			"David Rhind",
			"David Hubbell",
			"Guest (David Hubbell)",
		],
	},
	{
		number: 4,
		guests: [
			"Andrea Bric",
			"Andrew Bric",
			"Iva Dadic",
			"Ardavan Amirchoupani",
			"Misha Vickar",
			"Gil Segev",
			"Ivy Liang",
			"Karl Shao",
		],
	},
	{
		number: 5,
		guests: [
			"Salva Sadeghi",
			"Aaron Rosen",
			"Mahsa Sadeghi",
			"Nabil Ahrari",
			"Ziah Sumar",
			"Hafiz Kanji",
			"Asghar Sadeghi",
		],
	},
	{
		number: 6,
		guests: [
			"Haleh Shams-Hakimi",
			"Hamideh Shams-Hakimi",
			"Nika Shakiba",
			"Mario Moscovici",
			"Ava Moscovici",
			"Hossein Shakiba",
			"Narges Shams-Hakimi",
			"Doru Moscovici",
			"Violet Moscovici",
		],
	},
	{
		number: 7,
		guests: [
			"Fatemeh Jalaeikhoo",
			"Manoochehr Hamrahi",
			"Hossein Shalileh",
			"Sepideh Shayegan",
			"Giti Armaghani",
			"Mr. Torabi",
			"Mohammad Arastafar",
			"Mina Khanoom",
		],
	},
	{
		number: 8,
		guests: [
			"Amir Hossein Jalaeikhoo",
			"Faegheh Nozari",
			"Reza Shalileh",
			"Helen Lee",
			"Hamed Shalileh",
			"Tara Shojaei",
			"Mahtash Ardalan",
		],
	},
	{
		number: 9,
		guests: [
			"Hedieh Hamrahi",
			"Shahram Montazeri",
			"Nikko Montazeri",
			"Dean Montazeri",
			"Hormoz Hamrahi",
			"Parsi Mina",
			"Diako Hamrahi",
			"Kavian Hamrahi",
			"Andian Hamrahi",
		],
	},
	{
		number: 10,
		guests: [
			"Elham Taheri",
			"Ronald Wright",
			"Roya Homayoon",
			"Mansour Kohandani",
			"Lina Kohandani",
			"Diba Kohandani",
			"Ali Olfat",
		],
	},
	{
		number: 11,
		guests: [
			"Griffin Heyrich",
			"David Chu",
			"Hooman Keshvari",
			"Chris Drexler-Lemire",
			"Almendra Gonzales",
			"Denis Marchin",
			"Sanhee Marchin",
			"Daniel Shanker",
			"Allison Shanker",
		],
	},
	{
		number: 12,
		guests: [
			"Jaggi Dhaliwal",
			"Jas Dhaliwal",
			"Rajbir Dhaliwal",
			"Jas Gill",
			"Rupinder Gill",
			"Harbhajan Kaur Gill",
			"Kam Dhaliwal",
			"Harpreet Dhaliwal",
			"Ardaman Dhaliwal",
			"Arnoor Dhaliwal",
		],
	},
	{
		number: 13,
		guests: [
			"Paria Shahshahani",
			"Souren Khomarloo",
			"Keivan Torabi",
			"Kati Torabi",
			"Tara",
			"Behnam Esfahani",
			"Kiana Mostafavi",
			"Samyar Esfahani",
			"Sahand Esfahani",
		],
	},
	{
		number: 14,
		guests: [
			"Afshan Zahedi",
			"Saeed Ziaee",
			"Faraz Ziaee",
			"Raha Ziaee",
			"Kamran Sharifi",
			"Meeyoung",
			"Kiana Sharifi",
			"Ehsan Omidi",
			"Malihe Noroozian",
			"Ali Omidi",
		],
	},
	{
		number: 15,
		guests: [
			"Simar Chawla",
			"Tejinder Lamba",
			"Jasbir Lamba",
			"Jaipreet Lamba",
			"Harpreet Lamba",
			"Kirat Lamba",
			"Shabad Lamba",
			"Kamal Chawla",
			"DP Singh",
		],
	},
];

export type Table = {
	number: number;
	guests: string[];
};
